[package]
name = "player-io"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
gstd = { workspace = true, features = ["debug"] }
scale-info.workspace = true
parity-scale-codec.workspace = true
gmeta.workspace = true
syndote-io.workspace = true
